### ISSUE TITLE
How to build Installer?

### ISSUE THREAD

**Issue by Blexyel** [librespeed/speedtest-desktop#6]
I added a custom server and i want to properly install it on my windows machine, so i was just wondering how to build the installer.

**Comment by sudodios** [comment]
Hello @PassiHD2004 .
Unfortunately, jpackage does not have a good installer by default.
But this issue can be solved in a better way.
I am sorry that the configurations should be changed after installation (like adding custom servers).
If you have time, you can work on this and make a PR.

**Comment by Blexyel** [comment]
I can try to work on it, but i am very bad at coding, sooo.... Ill see what i can do

**Comment by sudodios** [comment]
@PassiHD2004 
Believe in yourself.
do your best

**Comment by Blexyel** [comment]
I'll try

**Comment by sudodios** [comment]
I will wait

**Comment by Blexyel** [comment]
i cant figure it out, the only problem is, is that the installer is not adding the app to the start menu....

and its impossible to find proper documentation about it.
![grafik](https://github.com/librespeed/speedtest-desktop/assets/59457929/95d7a848-03fc-4484-84b8-defbdc409add)

**Comment by Blexyel** [comment]
just confirmed the same behavior on my laptop, my windows on my pc is debloated with search indexing off and stuff, so just wanted to check it wasnt windows being wacky

**Comment by Blexyel** [comment]
and i dont know enough java/kotlin to make a proper global config, that doesnt require rebuilding. i feel way more at home in with rust, but i dont have the time and patience to make a client in rust at the moment. maybe some day!

**Comment by sudodios** [comment]
@PassiHD2004
This problem has nothing to do with the project itself, it is related to making an installer for jpackage. 
I don't have enough time now.  
I will solve this problem when I have a chance.

**Comment by Blexyel** [comment]
> @PassiHD2004
> This problem has nothing to do with the project itself, it is related to making an installer for jpackage. 
> I don't have enough time now.  
> I will solve this problem when I have a chance.

Alright, thx for the Info
